### PR TITLE
Fix examples for new process interface

### LINKED ISSUE #56: Examples broken as a consequence of commit 7827635
The signature of Process.__init__ no longer contains 'node_name', but the examples still try to pass it.

### PR DESCRIPTION
**Pull request by s2hc-johan**
fixes #56

### CODE REVIEW

**Comment by s2hc-johan** [comment]
Nope I'll fix. do we have documentation rebuild automatic, or do I need to rebuild ti myself?

**Comment by kvakvs** [comment]
From what i remember, docs are committed as part of the repository. I am not setting up unnecessary CI's and automatic builds where i can avoid.

**Comment by s2hc-johan** [comment]
fair enough, should I just run

```
make html
```
in the `doc-src` directory and then `cp build/html/* ../doc/` that changes a lot... Or am I missing some step?

Pushing the doc change I've made so far anyway

**Comment by s2hc-johan** [comment]
So should I push my build of the documentation, which changes more of the layout then what my actual doc src change are doing, or should I merge it as it, and maybe you @kvakvs can rebuild the doc from src

**Comment by kvakvs** [comment]
This PR has no changes to the documentation.
Do you want me to rebuild docs in the `master`?

**Comment by s2hc-johan** [comment]
small fix in cookbook, you could merge this one and rebuild

**Pull request merged**
